// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
var SquareVerifier = artifacts.require('SquareVerifier');
var Proof = require('../../zokrates/code/square/proof.json');

contract('TestSquareVerifier', accounts => {

    const account_one = accounts[0];
    const account_two = accounts[1];
    const account_three = accounts[2];
    const account_four = accounts[3];
    const account_five = accounts[4];
    const account_six = accounts[5];

    describe('Verifier Contract Tests', function () {
        beforeEach(async function () { 
            this.squareVerifier = await SquareVerifier.new({from: account_one});
        });
    
        // Test verification with correct proof
        // - use the contents from proof.json generated from zokrates steps
        it('Verify provided Proof for contract - SquareVerifier', async function () { 
           
           let result = await this.squareVerifier.verifyTx(Proof.proof.a,
                        Proof.proof.b, Proof.proof.c, Proof.inputs);
            console.log('Return value of verifyTx() function execution is '+result);
            console.log('Json stringify result 1 is '+JSON.stringify(result, null, 4)); //https://ethereum.stackexchange.com/questions/41270/solidity-function-returns-object-object
            assert.equal(result.logs[0].event, 'Verified','Verified event was not emitted - Proof failed');
            
        });

        it('Testing again with verifyTx.call() this time', async function () { 
           
            // Functions that do not require a transaction to be sent can be called directly with .call().
            let result = await this.squareVerifier.verifyTx.call(Proof.proof.a,
                         Proof.proof.b, Proof.proof.c, Proof.inputs);
            console.log('Return value of verifyTx() function execution is '+result);
            assert.equal(result, true,'Result should be true - Proof failed');  
        });


        // Test verification with incorrect proof
        it('Incorrect Proof verifyTx shall return false', async function () { 
            
            fakeProofInputs = [10,1];
            let result = await this.squareVerifier.verifyTx.call(Proof.proof.a,
                Proof.proof.b, Proof.proof.c, fakeProofInputs);
            console.log('The proof should fail and return false: result = '+result);
            assert.equal(result, false,'Result should have been false - Proof should not have passed');     
        });

    });
});





    

